lista = list()
print(type(lista))
lista.append(4)
print(lista)
lista.extend([4, "hola", 2, 0.1, "chao", 4])
print(lista)
lista.remove(4)
print(lista)
lista.pop(1)
print(lista)
print(len(lista))
print(lista)
print(lista.index("chao"))
print(lista.count(4))
lista2=[1, 2, 3]
print(lista2)
lista2.sort()
print(lista2)
nombre= "harold"
lista2.reverse()
print(lista2)
lista2.clear()
print(lista2)
del lista
print(lista) 
